name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "::add-matcher::${PWD}/.github/matchers.json"

      - name: Run a multi-line script
        run: printf '\e[31mHello\e[0m world!\n'
