name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Use a simple matcher
        run: echo "::add-matcher::${PWD}/.github/matchers.json"

      - name: Print some output that should match
        run: printf '\e[31mHello\e[0m world!\n'
